### PR TITLE
Add Ukrainian locale

### PR DESCRIPTION
**Pull request by Abrasha**
I have added Ukrainian locale. I have reviewed changes 3 times. But it will be awesome if somebody from Ukraine (or who knows Ukrainian well) will review these.

See the following issue: https://github.com/LonamiWebs/Stringlate/issues/146

### CODE REVIEW

**Comment by Lonami** [comment]
Tremendous! Thanks :)

> But it will be awesome if somebody from Ukraine (or who knows Ukrainian well) will review these.

So, should we merge or wait a bit longer?

**Comment by Abrasha** [comment]
We can merge this. I will later review Russian (because I found few typos there) and review Ukrainian one more time :)

My first `hacktoberfest` contribution :)

**Comment by Lonami** [comment]
Three to go :D

**Comment by gsantner** [comment]
@Abrasha If you want some more, here you go: <https://github.com/search?q=label%3Ahacktoberfest+user%3Agsantner+translate&state=open&type=Issues&utf8=%E2%9C%93>

**Comment by Abrasha** [comment]
@gsantner thank you. I have mentioned you in all repos.

**Pull request merged**
