### PR TITLE
Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by KevinSJ**

### CODE REVIEW

**Comment by XyLoNaMiyX** [comment]
Thanks!

**Comment by XyLoNaMiyX** [comment]
@KevinSJ mind translating these 5 strings before the next release?
```xml
<resources>
    <string name="allow_download_icons">Allow downloading icons</string>
    <string name="do_not_save">Don\'t save</string>
    <string name="save_count">Save (%d)</string>
    <string name="not_translated">Not translated.</string>
    <string name="search_id_content_ellipsis">Search by ID or content…</string>
</resources>
```

**Comment by KevinSJ** [comment]
Hi @XyLoNaMiyX , sorry about the delay but here are the translations:
```
<resources>
    <string name="allow_download_icons">允许下载图标</string>
    <string name="do_not_save">放弃修改</string>
    <string name="save_count">已保存 (%d)</string>
    <string name="not_translated">未翻译</string>
    <string name="search_id_content_ellipsis">使用ID或内容搜索…</string>
</resources>
```

**Comment by XyLoNaMiyX** [comment]
Don't worry, I admit I'm a bit impatient ;). I simply wanted to draft another release soon because it brings some big changes (and I like to have all the translations).

**Comment by XyLoNaMiyX** [comment]
Hello @KevinSJ would you mind updating your translation before the next `v0.9.5` release? You can either [translate this Gist](https://gist.github.com/XyLoNaMiyX/4aaab46a17514fb19d1ff1f0580dded9) or use Stringlate itself! Thank you.

**Pull request merged**
