### PR TITLE
Updated de (German) translation

### PR DESCRIPTION
**Pull request by squeezer11**
Commit made via Stringlate

### CODE REVIEW

**Comment by gsantner** [comment]
@Lonami not merge

**Comment by gsantner** [comment]
Quickly flied over it: Keep Repository as Repository, it makes life just harder to have multiple terms. translations like "Quelle, Aboholen, Einreichen" for Repository, Pull, Push are not needed

**Comment by gsantner** [comment]
@squeezer11 no need to close, you can also update the PR :)

**Comment by squeezer11** [comment]
hi, i have corrected now your translations wishes. also i have improved much more the german translations now. especially the german grammar. hope you are satisfied with the new improved and corrected translations.  

cheers!!!

**Pull request closed without merging**
