### PR TITLE
You've tagged 0.9.8 but these are not changed

### PR DESCRIPTION
**Pull request by licaon-kter**
not sure this is the reason F-Droid did not autoupdate though

### CODE REVIEW

**Comment by XyLoNaMiyX** [comment]
> not sure this is the reason F-Droid did not autoupdate though

Probably lol. Thanks.

**Comment by XyLoNaMiyX** [comment]
This is really going to take longer than expected, F-Droid guys need to accet the latest Android Support Repository license… Build log [here](https://f-droid.org/wiki/page/io.github.lonamiwebs.stringlate/lastbuild_981).

**Comment by licaon-kter** [comment]
That issue was not fixed yet?

**Comment by XyLoNaMiyX** [comment]
> That issue was not fixed yet?

They're constantly accepting licenses. Every time an Android library gets updated and a developer makes use of it, the license needs to be accepted again. Does not happen right away I guess.

**Pull request merged**
