### PR TITLE
add adaptive icon

### PR DESCRIPTION
**Pull request by connyduck**
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

### CODE REVIEW

**Comment by gsantner** [comment]
Can you show the icon screen which pops up when creating? See below for example from Markor: <https://github.com/gsantner/markor/issues/142#issuecomment-351825162>

**Comment by connyduck** [comment]
No because this wasnt made with asset studio. Here is a screenshot from my device (Android 8.1). Old icon left, new icon right. Signal isnt adaptive, the others are. 

screenshot_20180415-120919

**Comment by gsantner** [comment]
nice, how did you do the right-shadow?

**Comment by connyduck** [comment]
I edited the svg in Inkscape then used http://a-student.github.io/SvgToVectorDrawableConverter.Web/ (the converter built into Android Studio does not handle transformations correctly)

**Pull request merged**
