### PR TITLE
Add Romanian translation

### PR DESCRIPTION
**Pull request by licaon-kter**

### CODE REVIEW

**Comment by XyLoNaMiyX** [comment]
Thanks for all the effort you're putting into this project.

**Comment by licaon-kter** [comment]
Umm, I don't have that character on my Android keyboard (Google), maybe that's not a good idea, what's the gain here?

**Comment by XyLoNaMiyX** [comment]
Android Studio keeps complaining to use the ellipsis character over the three dots, also, and all the other locales use the ellipsis character too (yes, I replaced all the occurrences).

PS. Darn it, there's a missing ".." (not "...") on your translation. Oh well. Not a big deal is it?

**Comment by XyLoNaMiyX** [comment]
Hello @licaon-kter would you mind updating your translation before the next `v0.9.5` release? You can either [translate this Gist](https://gist.github.com/XyLoNaMiyX/4aaab46a17514fb19d1ff1f0580dded9) or use Stringlate itself! Thank you.

**Comment by licaon-kter** [comment]
Oh FFS 25% more? :-(

**Comment by XyLoNaMiyX** [comment]
You don't have to. When people sees missing translations they will (hopefully) add them ;)

Guess Stringlate wasn't a small app with only à few strings after all!

**Pull request merged**
