### PR TITLE
Add FAB feature 

### PR DESCRIPTION
**Pull request by diegoalvis**
Add floating action button for add project action and update java version

### CODE REVIEW

**Comment by gsantner** [comment]
Usually f-droid does not include beta/alpha versions of gradle, maybe ask in this case in irc. java 8 itself i think shouldnt be the problem

**Comment by diegoalvis** [comment]
@Lonami seems that there's no problem with java 8, and sure I'll use .svg file instead .png no worries!

**Comment by Lonami** [comment]
Just to be on the safe side. I have two complaints, the first being this:
image

Once I completely swipe to the other fragment, the fab is gone, but this empty space is still left there! So when there's a keyboard shown, it looks really odd. Maybe the FAB needs to be `GONE` and not `INVISIBLE`. Second complaint, do we need the swipping activity anymore as we have this new button? I thought the point behind adding the button was to remove the tabs ;)

If you remove the tabs and instead use say another activity to enter the details for a repository, you would get rid of the first complaint too as there there would be no FAB. Maybe we can merge "discover" and "enter URL" into a single activity with two tabs, so it could be:
* Main screen, single fragment. Only added repositories.
* Clicking on the FAB, new screen, two fragments. "Enter URL" one and another tab to "Discover".

**Comment by diegoalvis** [comment]
Main screen could be the history fragment right @Lonami ?

**Comment by Lonami** [comment]
Uhm yes I think it's called "history". It's just the "history" of repositories (projects) someone has added so far.

**Comment by diegoalvis** [comment]
I was checked and what you want is not a trivial change, the scope goes much more than just adding a fab button, for that reason I only made the change of visibility, but if you want a refactor of the structure of the app I suggest you divided into two or more specifics features

**Comment by Lonami** [comment]
Shall we merge this one then as a first step?

**Comment by diegoalvis** [comment]
Yes, but first check if visibility problem was salved with the last commit

**Comment by Lonami** [comment]
Tomorrow will do :)

**Comment by diegoalvis** [comment]
We should create a feature ticket for develop the new History Activity and another for create a new pager with the two fragments discover and enter url. Sure I will be pending

**Comment by Lonami** [comment]
The FAB issue is gone, thanks!

**Pull request merged**
