### PR TITLE
Updated tr (Turkish) translation

### PR DESCRIPTION
**Pull request by mission712**
Commit made via [Stringlate](https://lonamiwebs.github.io/stringlate/)
Meta-translation :P

### CODE REVIEW

**Comment by Lonami** [comment]
> Meta-translation

Hehe. Thank you for adding a whole new translation! Although it didn't make it to the `v0.11` it will be there on the next version :)

**Comment by Lonami** [comment]
Also fun fact: I was just opening GitHub to see if I had new notifications, and bam! Less than half a minute ago ^^

**Comment by mission712** [comment]
No problem. Amazing app, thanks.

**Comment by Lonami** [comment]
It's amazing thanks to the amazing people that use it to translate other projects, or spot bugs in it :)

**Pull request merged**
