### PR TITLE
Created a partial Norwegian translation

### PR DESCRIPTION
**Pull request by DandelionSprout**
I decided to make a quick translation of some parts of Stringlate.

You see, since I've so far used Stringlate as a detection tool to see which apps I have that have strings.xml files (which it works splendidly for), after which I head over to my PC to work on the translations there, it's therefore the various menus of Stringlate that I've focused on translating for now, and less so on the translation GUI. Hopefully that's understandable.

### CODE REVIEW

**Comment by Lonami** [comment]
> to see which apps I have that have strings.xml file

You might be interested in #46.

We can wait until you complete everything before we merge a partial translation.

**Comment by gsantner** [comment]
is this finished? not, right?

**Comment by DandelionSprout** [comment]
I had to prioritise a terrace renovation and some adblock filter lists instead, and once I'm finished with them I've got a scuba course book to read through. So unfortunately I've felt that I've had to take a break now from translation work in general.

**Comment by gsantner** [comment]
Sorry to hear that and have fun reading ;).

@Lonami  close or merge? Thinks this is roughly 40%

**Comment by Lonami** [comment]
No harm in keeping it open to track progress, for now.

**Comment by Lonami** [comment]
Stringlate says it's 100% now, so I guess it's true! Thank you.

**Comment by Lonami** [comment]
Oh damn. I forgot to change the commit title. Oops!

**Pull request merged**
