### PR TITLE
Meta PR: add fr translation

### PR DESCRIPTION
**Pull request by RomFouq**
I put `&#160;` for unbreakable space, I hope it'll do the trick.
French translation for your awesome translation app. ;-) :tada:

### CODE REVIEW

**Comment by XyLoNaMiyX** [comment]
Interesting thing about the `&#160;`. Thanks for the PR!

**Comment by XyLoNaMiyX** [comment]
@RomFouq would you mind translating these two strings?:
```xml
<resources>
    <string name="default_gist_share_description">strings.xml translation shared with Stringlate</string>
    <string name="translation_progress">%1$d/%2$d strings translated.</string>
</resources>
```

If you sync on Stringlate, they should show up as well.

**Comment by RomFouq** [comment]
I intentionally didn't translated the first string. I think it may be left in English since it's for the public Gist description and, in my opinion, should be international. So I think it could be marked as `translatable=false`.

For the second, I can make a PR if you prefer but it translates into `%1$d/%2$d chaînes traduites.`.

**Comment by XyLoNaMiyX** [comment]
> I think it may be left in English since it's for the public Gist description and, in my opinion, should be international.

Totally agree with you, I was thinking that also as I read the missing strings. Maybe I should remove the other translations and set it to `untranslatable="false"`… Yes, it will be a better choice. Good to know more people thinks that.

> For the second, I can make a PR if you prefer [...]

Nope, I actually prefer here, I have more strings modifications added on a local commit which is almost finished ;)

Thanks!

**Comment by XyLoNaMiyX** [comment]
@RomFouq new strings before the next release, only 5:
```xml
<resources>
    <string name="allow_download_icons">Allow downloading icons</string>
    <string name="do_not_save">Don\'t save</string>
    <string name="save_count">Save (%d)</string>
    <string name="not_translated">Not translated.</string>
    <string name="search_id_content_ellipsis">Search by ID or content…</string>
</resources>
```

**Comment by XyLoNaMiyX** [comment]
Thanks @RomFouq :+1:

**Comment by XyLoNaMiyX** [comment]
Hello @RomFouq would you mind updating your translation before the next `v0.9.5` release? You can either [translate this Gist](https://gist.github.com/XyLoNaMiyX/4aaab46a17514fb19d1ff1f0580dded9) or use Stringlate itself! Thank you.

**Pull request merged**
