### PR TITLE
Improved sloppy translation

### PR DESCRIPTION
**Pull request by Phoenix1747**
Corrected some serious grammatical and spelling mistakes. Looks much better now.

### CODE REVIEW

**Comment by Lonami** [comment]
Thanks!

**Comment by Lonami** [comment]
I hope `de` stands for `German` oops.

**Comment by gsantner** [comment]
Die Übersetzung war bewusst German-Du ;)

**Comment by Phoenix1747** [comment]
@gsantner Die Anspielung verstehe ich jetzt nicht? :S

**Comment by gsantner** [comment]
In Stringlate soll Deutsch-Du verwendet werden statt Deutsch-Sie/Höflichkeitsform

**Comment by Phoenix1747** [comment]
Achso, aber sonst wurde fast immer die Höflichkeitsform verwendet, weshalb ich dachte, dass es mehr angebracht wäre. Naja kann ich ja noch ändern.

**Comment by Lonami** [comment]
I'm understanding nothing. Could you please debate it in English?

**Comment by gsantner** [comment]
Ups, stimmt, wurde teilweise so, teilweise so gemacht. Aber dazu ist ein PR die beste Möglichkeit das zu vereinheitlichen :).

**Comment by gsantner** [comment]
We were discussing about two spoken german variants, and the non-uniformed current solution

**Comment by Phoenix1747** [comment]
Should we be using the more formal you or the informal you, there is a difference in German. Most of the translation contained the formal you and I corrected the rest which was still informal. The French translation also contains only the formal you, but @gsantner is saying that I should be using the informal version. What know @Lonami :P

**Comment by Lonami** [comment]
I don't really mind either versions, being consistent should be enough.

**Comment by Phoenix1747** [comment]
Ok then let's settle with the formal one, that looks like the most popular among the other translations.

**Comment by gsantner** [comment]
No, for buissness apps that is very okay, but this one is most targeted at personal users. Maybe also take a read at <https://forum.f-droid.org/t/du-oder-sie-in-uebersetzungen/567/11>

**Comment by Phoenix1747** [comment]
Yeah ok, but French and Spanish also use the formal form why would you now want to be so inconsistent? I'm sure other translations are also formal, but I don't want to look through them all.

**Comment by gsantner** [comment]
There is common solution to that, different countries, different users and culture. I think it's up to translators to find out whats best, and to know what they are used to (and especially in foss apps).

**Comment by Phoenix1747** [comment]
Ok then. It's up to @Lonami to decide I guess, but do what you have to do.

**Comment by Lonami** [comment]
Just be consistent ^^' I can only talk Spanish and English.

**Comment by Phoenix1747** [comment]
Yeah whatever, I corrected the file and made it consistent, that's all I wanted to do. If you want do make it informal then just do it @gsantner

**Pull request merged**
