### PR TITLE
Add zh-TW translation

### PR DESCRIPTION
**Pull request by Lin-Buo-Ren**
This translation is made using Stringlate itself.

Signed-off-by: 林博仁 &lt;<Buo.Ren.Lin@gmail.com>&gt;

### CODE REVIEW

**Comment by XyLoNaMiyX** [comment]
Thank you!

**Comment by XyLoNaMiyX** [comment]
Can you please translate these 5 before next release @Lin-Buo-Ren?
```xml
<resources>
    <string name="allow_download_icons">Allow downloading icons</string>
    <string name="do_not_save">Don\'t save</string>
    <string name="save_count">Save (%d)</string>
    <string name="not_translated">Not translated.</string>
    <string name="search_id_content_ellipsis">Search by ID or content…</string>
</resources>
```

**Comment by Lin-Buo-Ren** [comment]
```xml
<resources>
    <string name="allow_download_icons">允許下載應用軟體圖示</string> <!-- Assumed icons of apps -->
    <string name="do_not_save">不要儲存</string>
    <string name="save_count">儲存(%d)</string> <!-- Assumed modified translation string count -->
    <string name="not_translated">尚未被翻譯</string>
    <string name="search_id_content_ellipsis">根據識別名稱(ID)或內容來搜尋……</string>
</resources>
```

**Comment by XyLoNaMiyX** [comment]
Thanks @Lin-Buo-Ren ^^

**Comment by XyLoNaMiyX** [comment]
By the way,
```xml
<!-- Assumed modified translation string count -->
```

It means how many you've translated, but aren't saved yet. It has nothing to do with how many are translated in total (i.e. there might have been 50 translated, but you added 2 more and didn't save, so it will say "Save (2)".

**Comment by Lin-Buo-Ren** [comment]
> It means how many you've translated, but aren't saved yet. It has nothing to do with how many are translated in total (i.e. there might have been 50 translated, but you added 2 more and didn't save, so it will say "Save (2)".

Got it, not affecting the translation, though

**Comment by XyLoNaMiyX** [comment]
Awesome!

**Pull request merged**
